version: '3'

services:
  web:
    restart: always
    build: ./Docker
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html/project
    expose:
      - 80
        # stdin_open: true
        # tty: true
    # db:
    #     image: mariadb:10.2
    #     volumes:
    #         - db_data:/var/lib/mysql
te
